"""empty message

Revision ID: 18082d6d2067
Revises: 
Create Date: 2021-06-30 15:40:19.120936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18082d6d2067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('sudoku_score', sa.Integer(), nullable=False),
    sa.Column('chess_score', sa.Integer(), nullable=False),
    sa.Column('game_of_life_score', sa.Integer(), nullable=False),
    sa.Column('go_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
